packages:
  - "packages/*"
  - "packages/plugins/*"

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - node-pty
  - sharp

overrides:
  axios: "^1.15.0"
  "axios>follow-redirects": "^1.16.0"
  "external-editor>tmp": "0.2.4"
